CLIENT_ID = "YOURCLIENTID"
CLIENT_SECRET = "YOURCLIENTSECRET"
AUTH_URI = "https://YOURHOST/oxauth/restv1/authorize"
SCOPE = "openid profile"
RESPONSE_TYPE = "code"
REDIRECT_URI = "https://localhost:5000/callback"
TOKEN_ENDPOINT = "https://YOURHOST/oxauth/restv1/token"
USERINFO = 'https://YOURHOST/oxauth/restv1/userinfo'
SSL_VERIFY = False
